[package]
name = "Zmachine"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "30.0.1"
winit = "0.30.13"
pollster = "1.0.1"
bytemuck = { version = "1.25.2", features = ["derive"] }
glam = { version = "0.33.5", features = ["bytemuck"] }
env_logger = "0.11.11"
log = "0.4.34"
anyhow = "1.0.104"
cgmath = "0.18"
